const REQUEST_TIMEOUT_MS = 5000;
const PAGE_SIZE = 30;
const SEARCH_HOSTS = ['https://html.duckduckgo.com/html/', 'https://www.google.com/search'];
function decodeEntities(text=''){return text.replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#x27;|&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>');}
function stripHtml(text=''){return decodeEntities(text.replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim());}
function classify(url){const path=new URL(url).pathname.toLowerCase();if(/\/(reel|reels|tv)\//.test(path))return'reel';if(/\/p\//.test(path))return'post';return'profile';}
function cleanInstagramUrl(href){try{const raw=decodeEntities(href);const u=new URL(raw,'https://www.google.com');let candidate=u.hostname.includes('instagram.com')?u.href:u.searchParams.get('uddg')||u.searchParams.get('url');if(!candidate&&raw.includes('instagram.com/'))candidate=raw.slice(raw.indexOf('instagram.com/'));if(!candidate)return null;candidate=decodeURIComponent(candidate);if(!/^https?:\/\//i.test(candidate))candidate=`https://${candidate}`;const x=new URL(candidate);if(!x.hostname.toLowerCase().endsWith('instagram.com'))return null;const path=x.pathname.replace(/\/+$/,'')||'/';if(path==='/')return null;return `https://www.instagram.com${path}/`;}catch{return null;}}
function accountFromUrl(url){const p=new URL(url).pathname.split('/').filter(Boolean);return p[0]&&!['p','reel','reels','tv','explore'].includes(p[0].toLowerCase())?`@${p[0]}`:'';}
function queriesFor(q){const clean=q.replace(/^[@#]/,'').trim();if(q.startsWith('@'))return[`site:instagram.com/${clean}`,`site:instagram.com "${clean}"`];if(q.startsWith('#'))return[`site:instagram.com/explore/tags/${clean}`,`site:instagram.com/reel "${clean}"`,`site:instagram.com "#${clean}"`];return[`site:instagram.com "${q}"`,`site:instagram.com/reel "${q}"`,`site:instagram.com/p "${q}"`,`site:instagram.com "${q}" Instagram`];}
function collect(html,results,seen,limit){const re=/<a[^>]+href=["']([^"']*(?:instagram\.com|uddg=)[^"']*)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(html))&&results.length<limit){const url=cleanInstagramUrl(m[1]);if(!url||seen.has(url))continue;const title=stripHtml(m[2]||'')||url;seen.add(url);results.push({title:title.slice(0,220),snippet:'',url,account:accountFromUrl(url),kind:classify(url),source:'public search index'});}}
async function fetchPage(query,offset,host,headers){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),REQUEST_TIMEOUT_MS);try{const url=host.includes('duckduckgo')?`${host}?q=${encodeURIComponent(query)}&s=${offset}`:`${host}?q=${encodeURIComponent(query)}&start=${offset}`;const r=await fetch(url,{headers,signal:controller.signal});return r.ok?await r.text():null;}finally{clearTimeout(timer);}}
export async function discover({query,limit=20,maxPages=2}){const results=[],seen=new Set();const headers={'User-Agent':'Mozilla/5.0 (compatible; InstagramCrawler/1.0)','Accept':'text/html,application/xhtml+xml'};const searchedQueries=[];let pagesFetched=0,timedOut=false,successfulResponses=0;for(let page=0;page<maxPages&&results.length<limit;page++){const tasks=queriesFor(query).flatMap(q=>SEARCH_HOSTS.map(host=>(async()=>{searchedQueries.push({query:q,page:page+1,provider:host.includes('duckduckgo')?'duckduckgo':'google'});try{const html=await fetchPage(q,page*PAGE_SIZE,host,headers);if(html){successfulResponses++;pagesFetched++;collect(html,results,seen,limit);}}catch(e){if(e?.name==='AbortError')timedOut=true;}})()));await Promise.all(tasks);}return{results,pagesFetched,timedOut,successfulResponses,searchedQueries};}
export const name='public-search-index';
